### PR TITLE
Added support for Instagram video, amends to Users endpoint, Mapper and DamianM's fix for Media.Caption property

### PR DESCRIPTION
**Pull request by owenblacker**
This pull request includes a handful of bits and pieces but primarily:
- [DamianMac's fix](https://github.com/DamianMac/InstaSharp/commit/bd0c30274ddb412eb862524c5756c74f31e6ffbc)
  to correct the type of property `Media.Caption`
- Added support for Instagram videos, renaming `InstaSharp.Model.Image`
  to `InstaSharp.Model.MediaObject` and adding a new property
  `InstaSharp.Model.Media.Videos` of type `MediaObject`
- Allowed the
  [`Users...Recent` endpoint](http://instagram.com/developer/endpoints/users/#get_users_media_recent)
  to specify an optional User ID
- Overloaded the `Users...Recent` endpoint to take a `Nullable<DateTime>` where it previously took just a `DateTime`
- Removed superfluous and redundant User ID from
  [`Users...Feed` endpoint](http://instagram.com/developer/endpoints/users/#get_users_feed)
- Amended `Mapper.UnixTimeStampToDateTime` to use `DateTimeKind.Utc`
  instead of calling `DateTime.ToLocalTime`, per [Jon Skeet's answer](http://stackoverflow.com/a/7983514/205245) to a related StackOverflow question.

I also:
- Removed a bunch of files that probably shouldn't be tracked (the `bin` and `obj` contents, primarily)
- Hit "Remove and sort using directives" on the files I edited
- Set the [`AssemblyVersion`](http://msdn.microsoft.com/en-us/library/system.reflection.assemblyversionattribute.assemblyversionattribute.aspx) to `1.0.*` rather than `1.0.0.0`

### CODE REVIEW

**Comment by petemill** [comment]
Looks like the original repo isn't being maintained anymore. How about you guys with the pull requests switch to one of your repos as the primary project repo? Would be helpful for updating NuGet etc...

**Comment by owenblacker** [comment]
I can't promise to spend much time on it, but I'm happy to be the primary project repo, if there's a need for that. It's public at https://github.com/owenblacker/InstaSharp

**Comment by owenblacker** [comment]
(On that note, it's gonna be several days until I'm able to incorporate the other pull requests, mind, as a family member has a significant birthday this weekend  ;o)

**Comment by felipepessoto** [comment]
I am actively working in a fork, but I changed a lot of things, most of it is a break change:

-Converted to Portable Class Library
-Removed RestSharp in favor of HttpClient
-All calls are async
-Separate project for Tests
-Support for .NET 4, .NET 4.5, Silverlight 5, WP8, Windows Store 8

https://github.com/fujiy/InstaSharp

**Comment by owenblacker** [comment]
That very much sounds like you win, @fujiy  ;o)

**Comment by burkeholland** [comment]
Hi all! 

Reports of my death are greatly exaggerated yo!  I've been AFK and I'm terribly sorry.  I just don't have the time to give to this project anymore.  I'm happy to make @fujiy the owner here, but I would at least like to keep it in the same spot.  I'm flexible though.

@fujiy I created a r e-design branch which drastically changes the API and takes a dependency on RestSharp.  I also added full unit test (what what!!).  It's up to you how you want to proceed.  Either with pull requests, or with the API re-design - which I think is much better than the original structure.

**Comment by felipepessoto** [comment]
Hi @burkeholland 

I did all changes using re-design branch as base

**Comment by aupshaw** [comment]
Changes I made were minor.  Will probably be easier for me to check the redesign code after merges are in place.  Most of the stuff I needed was taken care of by OwenBlacker's updates. (Thanks!)  I'll keep watch on this project and if needed create a pull request for the re-design if anything seems left out.

**Comment by burkeholland** [comment]
@fujiy You have the keys to the kingdom...

**Comment by felipepessoto** [comment]
@owenblacker and @burkeholland I thinking about merging my code into re-design branch, what do you think? All current tests are passing. So @owenblacker can work at re-design branch too, since it has most of his changes

**Comment by burkeholland** [comment]
Sounds great!

Burke

**Comment by felipepessoto** [comment]
I am closing this topic. Most of the features are in re-deisgn branch. Please send pull requests based on that branch. Thx

**Pull request closed without merging**
